repos:
  - repo: local
    hooks:
      - id: lint
        name: Lint
        entry: yarn lint
        language: system
        pass_filenames: false

      # - id: snyk-dependency-scan
      #   name: Snyk dependency scan
      #   entry: snyk
      #   language: system
      #   args: ["test", "--severity-threshold=high"]
      #   pass_filenames: false

      # - id: snyk-code-scan
      #   name: Snyk code scan
      #   entry: snyk
      #   language: system
      #   args: ["code", "test", "--severity-threshold=high"]
      #   pass_filenames: false

  - repo: https://github.com/ministryofjustice/devsecops-hooks
    rev: v1.4.1
    hooks:
      - id: baseline