services:
  redis:
    image: redis/redis-stack:latest
    container_name: laa-claim-for-payment-redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5