{
 "title": "LAA Claim for Payment frontend - Service Health",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kube_deployment_metadata_generation,namespace)"
    }
   },
   {
    "name": "ingress",
    "query": {
     "query": "label_values(nginx_ingress_controller_requests{exported_namespace=\"$namespace\"},ingress)"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 1 },
   "options": {
    "content": "# LAA Claim for Payment Frontend Service Health"
   }
  },
  { "title": "Current State", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "Requests/sec",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(\n  rate(\n    nginx_ingress_controller_requests{\n      exported_namespace=\"$namespace\"\n    }[5m]\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "P95 Latency",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.95,\n  sum by (le) (\n    rate(\n      nginx_ingress_controller_request_duration_seconds_bucket{\n        exported_namespace=\"$namespace\"\n      }[5m]\n    )\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error rate %",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 *\nsum(\n  rate(\n    nginx_ingress_controller_requests{\n      exported_namespace=~\"$namespace\",\n      status=~\"5..\"\n    }[5m]\n  )\n)\n/\nsum(\n  rate(\n    nginx_ingress_controller_requests{\n      exported_namespace=~\"$namespace\"\n    }[5m]\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU %",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 *\nsum(\n  rate(\n    container_cpu_usage_seconds_total{\n      namespace=\"$namespace\"\n    }[5m]\n  )\n)\n/\nsum(\n  kube_pod_container_resource_limits{\n    namespace=\"$namespace\",\n    unit=\"core\"\n  }\n)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory %",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 *\nsum(\n  container_memory_usage_bytes{\n    namespace=~\"$namespace\"\n  }\n)\n/\nsum(\n  kube_pod_container_resource_limits{\n    namespace=~\"$namespace\",\n    unit=\"byte\"\n  }\n)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Available Pods",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  kube_pod_status_phase{\n    namespace=~\"$namespace\",\n    phase=\"Running\"\n  }\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Trends",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true
  },
  {
   "title": "Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "sum(\n  rate(\n    nginx_ingress_controller_requests{\n      exported_namespace=~\"$namespace\",\n      ingress=\"$ingress\"\n    }[5m]\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "P95 Latency Trend",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 20 },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.95,\n  sum by (le)(\n    rate(\n      nginx_ingress_controller_request_duration_seconds_bucket{\n        exported_namespace=\"$namespace\",\n        ingress=\"$ingress\",\n        path!~\"/socket.io/.*\"\n      }[5m]\n    )\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error rate trend",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 20 },
   "targets": [
    {
     "expr": "100 *\nsum(\n  rate(\n    nginx_ingress_controller_requests{\n      exported_namespace=\"$namespace\",\n      ingress=\"$ingress\",\n      status=~\"5..\"\n    }[5m]\n  )\n)\n/\nsum(\n  rate(\n    nginx_ingress_controller_requests{\n      exported_namespace=\"$namespace\",\n      ingress=\"$ingress\"\n    }[5m]\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}