{
 "title": "LAA Claim for Payment frontend - Service Health",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kube_deployment_metadata_generation,namespace)"
    }
   },
   {
    "name": "ingress",
    "query": {
     "query": "label_values(nginx_ingress_controller_requests{exported_namespace=\"$namespace\"},ingress)"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 0 },
   "options": {
    "content": "## LAA Claim for Payment Frontend Service Health"
   }
  },
  { "title": "Current State", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "Requests/sec",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(\n  rate(\n    nginx_ingress_controller_requests{\n      exported_namespace=\"$namespace\"\n    }[5m]\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "P95 Latency",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 4, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.95,\n  sum by (le) (\n    rate(\n      nginx_ingress_controller_request_duration_seconds_bucket{\n        exported_namespace=\"$namespace\"\n      }[5m]\n    )\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error rate %",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 9, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 *\nsum(\n  rate(\n    nginx_ingress_controller_requests{\n      exported_namespace=~\"$namespace\",\n      status=~\"5..\"\n    }[5m]\n  )\n)\n/\nsum(\n  rate(\n    nginx_ingress_controller_requests{\n      exported_namespace=~\"$namespace\"\n    }[5m]\n  )\n) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Authentication Failures (401) - Last 15 minutes",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 14, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  increase(\n    nginx_ingress_controller_requests{\n      exported_namespace=\"$namespace\",\n      ingress=\"$ingress\",\n      status=\"401\"\n    }[15m]\n  )\n) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Authorisation Failures (403) - Last 15 minutes",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  increase(\n    nginx_ingress_controller_requests{\n      exported_namespace=\"$namespace\",\n      ingress=\"$ingress\",\n      status=\"403\"\n    }[15m]\n  )\n) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Kubernetes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Available Pods",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  kube_pod_status_phase{\n    namespace=~\"$namespace\",\n    phase=\"Running\"\n  }\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU usage by pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 6, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "CPU cores" } },
   "targets": [
    {
     "expr": "sum by (pod) (\n  rate(\n    container_cpu_usage_seconds_total{\n      namespace=\"$namespace\",\n      container!=\"\"\n    }[5m]\n  )\n)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory usage by pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (pod) (\n  container_memory_usage_bytes{\n    namespace=\"$namespace\",\n    container!=\"\"\n  }\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Trends",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true
  },
  {
   "title": "Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "sum(\n  rate(\n    nginx_ingress_controller_requests{\n      exported_namespace=~\"$namespace\",\n      ingress=\"$ingress\"\n    }[5m]\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "P95 Latency Trend",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 19 },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.95,\n  sum by (le)(\n    rate(\n      nginx_ingress_controller_request_duration_seconds_bucket{\n        exported_namespace=\"$namespace\",\n        ingress=\"$ingress\",\n        path!~\"/socket.io/.*\"\n      }[5m]\n    )\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error rate trend",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 *\nsum(\n  rate(\n    nginx_ingress_controller_requests{\n      exported_namespace=\"$namespace\",\n      ingress=\"$ingress\",\n      status=~\"5..\"\n    }[5m]\n  )\n)\n/\nsum(\n  rate(\n    nginx_ingress_controller_requests{\n      exported_namespace=\"$namespace\",\n      ingress=\"$ingress\"\n    }[5m]\n  )\n) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Auth failures over time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 19 },
   "targets": [
    {
     "expr": "sum(\n  rate(\n    nginx_ingress_controller_requests{\n      exported_namespace=\"$namespace\",\n      ingress=\"$ingress\",\n      status=\"401\"\n    }[5m]\n  )\n) or vector(0)",
     "legendFormat": "401 Authentication"
    },
    {
     "expr": "sum(\n  rate(\n    nginx_ingress_controller_requests{\n      exported_namespace=\"$namespace\",\n      ingress=\"$ingress\",\n      status=\"403\"\n    }[5m]\n  )\n) or vector(0)",
     "legendFormat": "403 Authorisation"
    }
   ]
  }
 ]
}