apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "laa-claim-for-payment-frontend.fullname" . }}
  labels:
    {{- include "laa-claim-for-payment-frontend.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "laa-claim-for-payment-frontend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "laa-claim-for-payment-frontend.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "laa-claim-for-payment-frontend.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          env:
            - name: SERVICE_NAME
              value: "{{ .Values.env.SERVICE_NAME }}"
            - name: SERVICE_PHASE
              value: "{{ .Values.env.SERVICE_PHASE }}"
            - name: DEPARTMENT_NAME
              value: "{{ .Values.env.DEPARTMENT_NAME }}"
            - name: DEPARTMENT_URL
              value: "{{ .Values.env.DEPARTMENT_URL }}"
            - name: CONTACT_EMAIL
              value: "{{ .Values.env.CONTACT_EMAIL }}"
            - name: CONTACT_PHONE
              value: "{{ .Values.env.CONTACT_PHONE }}"
            - name: SERVICE_URL
              value: "{{ .Values.env.SERVICE_URL }}"
            - name: SESSION_SECRET
              value: "{{ .Values.env.SESSION_SECRET }}"
            - name: SESSION_NAME
              value: "{{ .Values.env.SESSION_NAME }}"
            - name: RATELIMIT_HEADERS_ENABLED
              value: "{{ .Values.env.RATELIMIT_HEADERS_ENABLED }}"
            - name: RATELIMIT_STORAGE_URI
              value: "{{ .Values.env.RATELIMIT_STORAGE_URI }}"
            - name: RATE_LIMIT_MAX
              value: "{{ .Values.env.RATE_LIMIT_MAX }}"
            - name: RATE_WINDOW_MS
              value: "{{ .Values.env.RATE_WINDOW_MS }}"
            - name: API_URL
              value: "{{ .Values.env.API_URL }}"
            - name: NODE_ENV
              value: "{{ .Values.env.NODE_ENV }}"
            - name: AUTH_ENABLED
              value: "{{ .Values.env.AUTH_ENABLED }}"
            - name: ISSUER_BASE_URL
              value: "{{ .Values.env.ISSUER_BASE_URL }}"
            - name: CLIENT_ID
              value: "{{ .Values.env.CLIENT_ID }}"
            - name: USE_SSL
              value: "{{ .Values.env.USE_SSL }}"
            - name: OIDC_SCOPE
              value: "{{ .Values.env.OIDC_SCOPE }}"
            - name: OIDC_LOGIN_PATH
              value: "{{ .Values.env.OIDC_LOGIN_PATH }}"
            - name: OIDC_CALLBACK_PATH
              value: "{{ .Values.env.OIDC_CALLBACK_PATH }}"
            - name: OIDC_LOGOUT_PATH
              value: "{{ .Values.env.OIDC_LOGOUT_PATH }}"
            - name: OIDC_CLIENT_SECRET
              value: "{{ .Values.env.OIDC_CLIENT_SECRET }}"      
   
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
