name: Mocha Unit tests
on:
  workflow_dispatch: # Allow manual triggering only
    inputs:
      environment:
        description: 'Deployment environment'
        required: false
        default: 'uat'
  workflow_call: # Allow this workflow to be called by other workflows

jobs:
  mocha-unit-tests:
    name: Mocha Unit Tests
    runs-on: ubuntu-latest
    env:
      REDIS_DISABLED: "true" # Disable Redis for testing
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd #v6.0.2

      - name: Setup Node + Yarn
        uses: ./.github/actions/setup_npm_and_yarn
        with:
          node-version: '24.2.0'
          working-directory: .

      - name: SLSA
        uses: ministryofjustice/devsecops-actions/sca/slsa@4cd163be7859cd130800d6719d925318826038ea

      - name: Install dependencies
        run: yarn install --immutable

      - name: Build
        run: yarn build

      - name: Run Mocha unit tests
        run: yarn coverage

      - name: Upload coverage report
        if: always()
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a #v7.0.1
        with:
          name: coverage-report
          path: coverage

