name: ZAP
on:
  schedule:
    - cron: "0 0 * * 1-5"
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to run the workflow on (default: main)'
        required: false
        default: 'main'
jobs:
  zap_scan:
    name: Scan the web application
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd #v6.0.2
      - name: Trigger ZAP workflow run
        uses: ./.github/actions/trigger_workflow
        with:
          app-id: ${{ secrets.APP_ID }}
          app-private-key: ${{ secrets.APP_PRIVATE_KEY }}
          org: ministryofjustice
          repo: claim-assess-regression-tests
          workflow: zap.yml
          ref: main
          extra-args: '-f target="http://localhost:3000" -f application="laa-claim-for-payment-frontend"'
